/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Generator:     sensirion-driver-generator 1.3.3
 * Product:       sps30
 * Model-Version: 1.0.1
 */
/*
 * Copyright (c) 2025, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
#include "sensirion_common.h"
#include "sensirion_i2c_hal.h"
#include "sps30_i2c.h"
#include <inttypes.h>  // PRIx64
#include <stdio.h>     // printf

#define sensirion_hal_sleep_us sensirion_i2c_hal_sleep_usec

int main(void) {
    int16_t error = NO_ERROR;
    sensirion_i2c_hal_init();
    sps30_init(SPS30_I2C_ADDR_69);

    sps30_stop_measurement();
    int8_t serial_number[32] = {0};
    int8_t product_type[8] = {0};
    sps30_read_serial_number(serial_number, 32);
    printf("serial_number: %s\n", serial_number);
    sps30_read_product_type(product_type, 8);
    printf("product_type: %s\n", product_type);
    sps30_start_measurement((sps30_output_format)(1280));
    sensirion_hal_sleep_us(100000);
    uint16_t data_ready_flag = 0;
    uint16_t mc_1p0 = 0;
    uint16_t mc_2p5 = 0;
    uint16_t mc_4p0 = 0;
    uint16_t mc_10p0 = 0;
    uint16_t nc_0p5 = 0;
    uint16_t nc_1p0 = 0;
    uint16_t nc_2p5 = 0;
    uint16_t nc_4p0 = 0;
    uint16_t nc_10p0 = 0;
    uint16_t typical_particle_size = 0;
    uint16_t repetition = 0;
    for (repetition = 0; repetition < 50; repetition++) {
        sensirion_hal_sleep_us(1000000);
        error = sps30_read_data_ready_flag(&data_ready_flag);
        if (error != NO_ERROR) {
            printf("error executing read_data_ready_flag(): %i\n", error);
            continue;
        }
        printf("data_ready_flag: %u\n", data_ready_flag);
        error = sps30_read_measurement_values_uint16(
            &mc_1p0, &mc_2p5, &mc_4p0, &mc_10p0, &nc_0p5, &nc_1p0, &nc_2p5,
            &nc_4p0, &nc_10p0, &typical_particle_size);
        if (error != NO_ERROR) {
            printf("error executing read_measurement_values_uint16(): %i\n",
                   error);
            continue;
        }
        printf("mc_1p0: %u ", mc_1p0);
        printf("mc_2p5: %u ", mc_2p5);
        printf("mc_4p0: %u ", mc_4p0);
        printf("mc_10p0: %u ", mc_10p0);
        printf("nc_0p5: %u ", nc_0p5);
        printf("nc_1p0: %u ", nc_1p0);
        printf("nc_2p5: %u ", nc_2p5);
        printf("nc_4p0: %u ", nc_4p0);
        printf("nc_10p0: %u ", nc_10p0);
        printf("typical_particle_size: %u\n", typical_particle_size);
    }

    error = sps30_stop_measurement();
    if (error != NO_ERROR) {
        return error;
    }
    return NO_ERROR;
}
