CMAKE_MINIMUM_REQUIRED(VERSION 3.22)
# Enable CMake support for ASM and C languages
ENABLE_LANGUAGE(C ASM)
INCLUDE(../scope-share.cmake)
STM_SET_LIBNAME()

# Interface library for includes and symbols
ADD_LIBRARY(${INTERFACE_NAME} INTERFACE)
SET(DRIVERS_ROOT_DIR "${PROJECT_ROOT_DIR}/Drivers")
TARGET_INCLUDE_DIRECTORIES(${INTERFACE_NAME} INTERFACE
        ${DRIVERS_ROOT_DIR}/RTT/8.58.0/RTT
)

# Create STM32_Drivers static library
ADD_LIBRARY(${LIBRARY_NAME} OBJECT)
TARGET_INCLUDE_DIRECTORIES(${LIBRARY_NAME} PRIVATE
        ${DRIVERS_ROOT_DIR}/RTT/8.58.0/Config
        ${DRIVERS_ROOT_DIR}/RTT/8.58.0/RTT

)
TARGET_SOURCES(${LIBRARY_NAME} PRIVATE
        ${DRIVERS_ROOT_DIR}/RTT/8.58.0/RTT/SEGGER_RTT.c
        ${DRIVERS_ROOT_DIR}/RTT/8.58.0/RTT/SEGGER_RTT_printf.c
)

# Add libraries to the project
TARGET_LINK_LIBRARIES(${CMAKE_PROJECT_NAME}
        ${LIBRARY_NAME}
)
