    MACRO(STM_SET_LIBNAME)
        GET_FILENAME_COMPONENT(LIBRARY_NAME ${CMAKE_CURRENT_LIST_DIR} NAME)
    ENDMACRO(STM_SET_LIBNAME)
    GET_FILENAME_COMPONENT(PROJECT_ROOT_DIR ${CMAKE_CURRENT_LIST_DIR} DIRECTORY)

    SET(APP_ROOT_DIR ${CMAKE_CURRENT_LIST_DIR})
