CMAKE_MINIMUM_REQUIRED(VERSION 3.22)
# Enable CMake support for ASM and C languages
ENABLE_LANGUAGE(C ASM)
INCLUDE(../scope-share.cmake)
STM_SET_LIBNAME()

# Interface library for includes and symbols
ADD_LIBRARY(${INTERFACE_NAME} INTERFACE)
TARGET_INCLUDE_DIRECTORIES(${INTERFACE_NAME} INTERFACE
        ${DRIVERS_ROOT_DIR}/BME68x/4.4.8
        ${DRIVERS_ROOT_DIR}/BSEC/2.6.1.0/inc
        ${DRIVERS_ROOT_DIR}/BSEC/2.6.1.0/config/bme680_iaq_33v_3s_4d
)
TARGET_LINK_LIBRARIES(${INTERFACE_NAME} INTERFACE
        ${LIBRARY_NAME}
)

# Create STM32_Drivers static library
ADD_LIBRARY(${LIBRARY_NAME} OBJECT)
TARGET_INCLUDE_DIRECTORIES(${LIBRARY_NAME} PRIVATE
        ${DRIVERS_ROOT_DIR}/BME68x/4.4.8
        ${DRIVERS_ROOT_DIR}/BSEC/2.6.1.0/config/bme680_iaq_33v_3s_4d
        ${DRIVERS_ROOT_DIR}/BSEC/2.6.1.0/inc
)
TARGET_SOURCES(${LIBRARY_NAME} PRIVATE
        ${DRIVERS_ROOT_DIR}/BME68x/4.4.8/bme68x.c
        ${DRIVERS_ROOT_DIR}/BSEC/2.6.1.0/config/bme680_iaq_33v_3s_4d/bsec_iaq.c
)
TARGET_LINK_DIRECTORIES(${LIBRARY_NAME} PUBLIC
        ${DRIVERS_ROOT_DIR}/BSEC/2.6.1.0/Cortex_M4F
)

TARGET_LINK_LIBRARIES(${LIBRARY_NAME} PUBLIC
        algobsec
)

# Add libraries to the project
TARGET_LINK_LIBRARIES(${CMAKE_PROJECT_NAME}
        ${LIBRARY_NAME}
)
